[tool.poetry]
name = "lablib"
version = "0.0.1-dev.1"
description = ""
authors = ["doerp <me@doerp.cool>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
